#!/bin/bash
#
# Init script for elasticarmor
# For more information please see https://www.netways.org/projects/elasticarmor
#
# chkconfig:   2345 80 20
# description: Start/Stop elasticarmor
#
### BEGIN INIT INFO
# Provides:          elasticarmor
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     false
# Short-Description: Start/Stop elasticarmor
# Description:       Start or stop the elasticarmor proxy daemon
#  This script will start the proxy daemon and provide the mandatory
#  options like status and restart
### END INIT INFO

set -e

case "$1" in
    force-reload)
        /usr/bin/python2 -m elasticarmor.elasticarmord -u elasticarmor -g elasticarmor -b "restart"
        exit $?
    ;;
    start|restart)
        /usr/bin/python2 -m elasticarmor.elasticarmord -u elasticarmor -g elasticarmor -b "$1"
        exit $?
    ;;
    stop|reload|status)
        /usr/bin/python2 -m elasticarmor.elasticarmord "$1"
        exit $?
    ;;
    *)
        echo "Usage: $0 {start|stop|reload|force-reload|restart|status}"
        exit 1
    ;;
esac
